version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"
    restart: unless-stopped
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    ports:
      - "5173:5173"
    restart: unless-stopped
